SAUDI_BANK_CODES = {
            "01": "Saudi National Bank (SNB - AlAhli)",
            "02": "Saudi British Bank (SABB)",
            "03": "Saudi Investment Bank (SAIB)",
            "04": "Alinma Bank",
            "05": "Banque Saudi Fransi (BSF)",
            "06": "Arab National Bank (ANB)",
            "07": "Riyad Bank",
            "08": "Al Rajhi Bank",
            "09": "Bank AlJazira",
            "10": "Gulf International Bank (GIB)",
            "11": "First Abu Dhabi Bank (FAB) - Saudi Branch",
            "12": "Emirates NBD - Saudi Branch",
            "13": "Alawwal Bank (Merged with SABB)",
            "14": "National Bank of Bahrain (NBB) - Saudi Branch",
            "15": "JPMorgan Chase - Saudi Branch",
            "16": "Deutsche Bank - Saudi Branch",
            "17": "HSBC Saudi Arabia",
            "18": "Standard Chartered - Saudi Branch",
            "19": "Bank Albilad",
            "20": "Saudi EXIM Bank",
        }
