# Execution Default Configurations
DEFAULT_WAIT_ELEMENT_STATE_TIMEOUT = '5s'
DEFAULT_WAIT_PAGE_LOAD_TIMEOUT = '10s'
DEFAULT_SCREENSHOT_TIMEOUT = '10s'
DEFAULT_WAIT_NETWORK_IDLE_TIMEOUT = '60s'
DEFAULT_WAIT_FLAKY_ELEMENT_STATE_TIMEOUT = '60s'
DEFAULT_WAIT_UNSTABLE_PAGE_LOAD_TIMEOUT = '120s'
DEFAULT_UNSTABLE_ELEMENT_SCREENSHOT_TIMEOUT = '60s'

# Default Actions
DEFAULT_SINGLE_KEY_STROKES = '0.1s'
DEFAULT_MOUSE_CLICK_ACTION = 'left'
DEFAULT_NUMBER_OF_MOUSE_CLICKS = 1

# Default Test Timeouts
DEFAULT_WAIT_PAGE_BEHAVIOR = 'domcontentloaded'
DEFAULT_WAIT_PAGE_NETWORK_IDLE_BEHAVIOR = "networkidle"
DEFAULT_WAIT_PAGE_COMMIT_BEHAVIOR = 'commit'

# Default Element State
DEFAULT_ELEMENT_STATE = 'visible'
DEFAULT_ELEMENT_ENABLED_STATE = 'enabled'
DEFAULT_ELEMENT_VISIBLE_STATE = 'visible'
DEFAULT_DISABLED_ELEMENT_STATE = 'disabled'
DEFAULT_CHECKBOX_STATE = 'checked'
ELEMENT_DOES_NOT_EXIST_STATE = 'detached'

# Elements Default Configurations
DEFAULT_CLEAR_INPUT_FIELD_ACTION = True
DEFAULT_SCREENSHOT_IMAGE_EXTENSION = 'png'

# Default File Encoding
DEFAULT_FILE_ENCODING = 'UTF-8'

# HTML Tags
DEFAULT_GENERIC_ELEMENT_TAG = '*'
LIST_ITEM_TAG = 'li'
GENERIC_BUTTON_TAG = 'button'
GENERIC_INPUT_TAG = 'input'

# Element Attribute
NAME_ATTRIBUTE = '@name'
PLACE_HOLDER_ATTRIBUTE = '@placeholder'
CLASS_ATTRIBUTE = '@class'
TEXT_ATTRIBUTE = 'text()'
NORMALIZED_SPACE_ATTRIBUTE = 'normalized-space()'
TEXT_ATTRIBUTE_WITH_NORMALIZED_SPACES = 'normalize-space(text())'

# File Extension
DEFAULT_FILE_EXTENSION = '*'
VIDE0_RECORDING_EXTENSION = '.webm'

# String Separators
DEFAULT_PATH_SEPERATOR = '\\'
DEFAULT_FILE_SEPERATOR = 'Tests_Configurations'
DEFAULT_SPACE_FILLER = '_'

DEFAULT_AR_LETTERS = "أبتثجحخدذرزسشصضطظعغفقكلمنهويإلإءئ"
DEFAULT_EN_LETTERS = "ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz"
DEFAULT_RANDOM_NUMBERS_ARG = '[NUMBERS]'
DEFAULT_EN_LOWER_LETTERS = "abcdefghijklmnopqrstuvwxyz"
DEFAULT_EN_UPPER_LETTERS = "ABCDEFGHIJKLMNOPQRSTUVWXYZ"
DEFAULT_ALLOWED_SPECIAL_CHARACTERS = "$@&"

# Platform Configurations
DEFAULT_LANGUAGE = "عربي"
